# Generated by Django 3.2.7 on 2022-06-23 18:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220623_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='describe',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
